### ISSUE TITLE
Index matching should use "starts with"

### ISSUE THREAD

**Issue by nommaz** [nommaz/ownslack#3]
Sorry I think I wasnt clear enough with index matching. It should be starts with with not equals.

Examples:
/Yazılım/Release/X900/Utils/EJReader/ejReader_v101.zip is failing but should match /Yazılım/Release/X900/ and post to devkf.

It should always select the longest index out of all matches and post there. So first check /Yazılım/Release/X900/, if index does not exist, check /Yazılım/Release/, and finally check /Yazılım/

Hope thats clear.

Full error log:
[errors.txt](https://github.com/nommaz/ownslack/files/768270/errors.txt) the index with dir/subdir/subsubdir/subsubsubdir is failing as

**Comment by VimalKP** [comment]
i have added code for choosing right channel now... please pull and have a look @nommaz

**Comment by VimalKP** [comment]
solved please check
