### ISSUE TITLE
Post styling

### ISSUE THREAD

**Issue by nommaz** [nommaz/ownslack#4]
The style of the post should be more detailed with description including full path and file size and also with file icon according to the specification

**Comment by nommaz** [comment]
Current: 
<img width="500" alt="current" src="https://cloud.githubusercontent.com/assets/10116478/22860955/af383140-f11d-11e6-9b3c-11bf0b1c4bff.png">

Ideal:
<img width="581" alt="ideal" src="https://cloud.githubusercontent.com/assets/10116478/22860970/073051ac-f11e-11e6-81ba-54787386aab8.png">

**Comment by VimalKP** [comment]
@nommaz - the style you provided was only possible if we upload File Real time in Slack.
we are just display as attachment. and in my Current example i have already used "attachment" function as you have provided.

Here is what we can do maximum with Attachment parameter.
Below sample uses all available parameters in Attachment.. so we can only from this style : 
![attachment](https://cloud.githubusercontent.com/assets/4170387/22925703/c180f07c-f2cf-11e6-91ec-11d79eea2739.PNG)

**Comment by VimalKP** [comment]
https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22pretext%22%3A%22file_changed%22%2C%22title%22%3A%22Requirement%20-%20owncloud%20to%20slack.docx%22%2C%22title_link%22%3A%22https%3A%2F%2Fdocs.hugin.co%2Findex.php%2Fapps%2Fonlyoffice%2F119994%22%2C%22footer%22%3A%2264.31%20KB%20%2FYaz%C4%B1l%C4%B1m%2FProject%22%2C%22footer_icon%22%3A%22https%3A%2F%2Fdocs.hugin.co%2Fapps%2Fslack%2F12.png%22%7D%5D%7D
