### ISSUE TITLE
Incrementing max_update_id one at a time

### ISSUE THREAD

**Issue by nommaz** [nommaz/ownslack#5]
**First run:**
vedat APP [10:55 AM]
iade_islemi_gelistirme_adımları.docx file_changed
iade_islemi_gelistirme_adımları.docx file_created
iade_islemi_gelistirme_adımları.docx.d1486825016 file_created
BOOKING POLICY.pdf file_created
Code 128 barkod ile satış.docx file_changed
install.txt file_changed
install.txt file_changed
*serdar APP [10:55 AM]*
FPUDev_v426.rar file_created

**Second run:** (should have been completely empty because no new files)
vedat APP [10:55 AM] 
iade_islemi_gelistirme_adımları.docx file_changed
iade_islemi_gelistirme_adımları.docx file_created
iade_islemi_gelistirme_adımları.docx.d1486825016 file_created
BOOKING POLICY.pdf file_created
Code 128 barkod ile satış.docx file_changed
install.txt file_changed
install.txt file_changed

**Third run:** (should have been completely empty because no new files)
vedat APP [10:56 AM] 
iade_islemi_gelistirme_adımları.docx file_changed
iade_islemi_gelistirme_adımları.docx file_created
iade_islemi_gelistirme_adımları.docx.d1486825016 file_created
BOOKING POLICY.pdf file_created
Code 128 barkod ile satış.docx file_changed
install.txt file_changed

**Fourth run:** (should have been completely empty because no new files)
vedat APP [10:57 AM] 
iade_islemi_gelistirme_adımları.docx file_changed
iade_islemi_gelistirme_adımları.docx file_created
iade_islemi_gelistirme_adımları.docx.d1486825016 file_created
BOOKING POLICY.pdf file_created
Code 128 barkod ile satış.docx file_changed

**Comment by VimalKP** [comment]
you need to update query to get record ASC mode to solve this issue.
i just commited please pull the code,
