### ISSUE TITLE
does not prepend text according to requirement 2.3.1.

### ISSUE THREAD

**Issue by nommaz** [nommaz/ownslack#9]

**Comment by VimalKP** [comment]
So, in header only **object_id** is dynamic or anything else need to be generate dynamically ?
here is header i am using now 
`Content from docs\.hugin\.co [Edit] (https://docs.hugin.co/index.php/apps/files/?fileid={{object_id}})`

**Comment by nommaz** [comment]
this looks correct but i dont think you can have space between ] and (

**Comment by VimalKP** [comment]
okay... will remove that space.

`Content from docs\.hugin\.co [Edit](https://docs.hugin.co/index.php/apps/files/?fileid={{object_id}})`
